apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dara-kok5367-spring-mybati
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/dara-kok5367-spring-mybati.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dara-kok5367-spring-mybati
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
