apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dara-kok5367-spring-mybati-certificate
  namespace: dara-kok5367-spring-mybati
spec:
  secretName: dara-kok5367-spring-mybati-secret-tls
  commonName: dara-kok5367-spring-mybati.assessify.org
  dnsNames:
  - dara-kok5367-spring-mybati.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
